import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import random
from math import sqrt


## All functions definition
def load_an_image(fichier):
    '''Cette fonction récupère la liste des pixels d'une image à partir du fichier à l'emplacement fourni
    Args :
        fichier (str): emplacement de l'image
    Returns:
        Liste des pixels de l'image '''
    img = mpimg.imread(fichier)
    return img


def display_an_image(img):
    '''This function displays the image img
    Args:
        img(list): list of pixels of img
    Returns:
        No return, just display the image img'''
    plt.imshow(img)
    plt.show()



def display_images(Liste_img):
    '''This function displays the images that are in the list Liste_img
    Args:
        Liste_img (list): List of images (an image = a list of pixels)
    Returns:
        No return, just display the images that are in Liste_img'''
    n = len(Liste_img)
    dim = int(sqrt(n))+1
    fig = plt.figure()
    i = 0
    for img in Liste_img:
        fig.add_subplot(dim, dim, i+1)
        plt.title(f"Image {i+1}")
        plt.imshow(img)
        i += 1
    plt.show()


#def store_image_jpg(img):



def images_init(n):
    '''This function selects n random images in the database (202599 images) to initiate the processus of selection by the user
    Args:
        n(int): number of images we want to be displayed at the beginning
    Returns :
        list : lists of pixels of the n images selected randomly
    '''
    List_images = []
    for i in range(n):
        num = random.randint(1,202599)
        if num > 100000:
            img = mpimg.imread(f'D:/Noemie/Documents/Biosciences/4A-S2/Développement Logiciel - Projet 4BIM/Projet 4BIM/img_align_celeba/{num}.jpg')
        elif num > 10000:
            num = f'0{num}'
        elif num > 1000:
            num = f'00{num}'
        elif num > 100:
            num = f'000{num}'
        elif num > 10:
            num = f'0000{num}'
        else:
            num = f'00000{num}'
        img = mpimg.imread(f'D:/Noemie/Documents/Biosciences/4A-S2/Développement Logiciel - Projet 4BIM/Projet 4BIM/img_align_celeba/{num}.jpg')
        plt.imshow(img)
        List_images.append(img)
    return List_images



def user_choice(List_images, n):
    '''This function asks the user to choose between len(List_images) images the n images that are the closest to the suspect
    Args:
        List_images (list): List of images displayed on the screen, generated by the algorithm or randomly chosen in the database
        n (int): number of images  to be chosen by the user, has to be < len(List_images)
    Returns:
        list : list of images (an image = a list of pixels) chosen by the user'''
    List_num = []
    List_images_chosen = []
    str_images_chosen = input(f"Choose {n} images among those displayed that are the closest to the suspect and write the position of each image chosen separated by a space (ex : 1 5 = 1st image, 5th one, in the order of appearance) :  ")
    List_num_str = str_images_chosen.split(' ')
    for element in List_num_str:
        List_num.append(int(element))
    for number in List_num :
         i = number - 1
         List_images_chosen.append(List_images[i])
    return List_images_chosen



def Recup_list_attributs(fichier):
    '''This function reads the file list_attr_celeba.txt and stores the information that are in in a list
    Args:
        fichier(str) : chemin d'accès du fichier
    Returns:
        List_attributs (list) = list of 1 and -1 for each image, 1st row = name of the attribute, 1st element of each row (except n°0) = name of the image'''
    with open(fichier) as annotations:
        List_attributs = []
        for ligne in annotations:
            L = ligne.split(' ')
            L1 = []
            for element in L:
                if element != '':
                    L1.append(element)
            if len(L1) > 2:
                List_attributs.append(L1)
    return List_attributs



def Recup_attributs(attribut, List_attributs):
    '''This function stores in a dictionary the value of the attribute "attribut" for each image (key = str of the name of the image)
    Args:
        attribut (str):str representing the name of an attribute among  ("5_o_Clock_Shadow", "Arched_Eyebrows", "Attractive", "Bags_Under_Eyes", "Bald", "Bangs", "Big_Lips", "Big_Nose", "Black_Hair", "Blond_Hair", "Blurry", "Brown_Hair", "Bushy_Eyebrows", "Chubby", "Double_Chin", "Eyeglasses", "Goatee", "Gray_Hair", "Heavy_Makeup", "High_Cheekbones", "Male", "Mouth_Slightly_Open", "Mustache", "Narrow_Eyes", "No_Beard", "Oval_Face", "Pale_Skin", "Pointy_Nose", "Receding_Hairline", "Rosy_Cheeks", "Sideburns", "Smiling", "Straight_Hair", "Wavy_Hair", "Wearing_Earrings", "Wearing_Hat", "Wearing_Lipstick", "Wearing_Necklace", "Wearing_Necktie", "Young")
        List_attributs (list): List representing the file with all the attributes, with values 1 if the attribute is present, -1 if it is not
    Returns:
        Dico_attribut (dictionary): dictionary whose keys are the name of the image (ex: "000001.jpg") and the values are -1 or 1 (1 if attribute present, -1 otherwise)'''
    Dico_attribut = {}
    i = 0
    for element in List_attributs[0]:
        if element == attribut:
            break
        else:
            i += 1
    for image in List_attributs[1:-1] :
        num_image = image[0]
        Dico_attribut[num_image] = int(image[i+1])
    return Dico_attribut
